name: Auto Commit Random Natural

on:
  schedule:
    - cron: "0 0 * * *" # start tiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Random Delay Sebelum Mulai
        run: |
          # Random delay sebelum mulai commit (0–8 jam)
          DELAY=$(( RANDOM % 28800 )) # 28800 detik = 8 jam
          echo "Menunggu $DELAY detik (~$((DELAY/3600)) jam) sebelum mulai..."
          sleep $DELAY

      - name: Random Commit
        run: |
          git config --global user.name 'Yawwnann (Bot)'
          git config --global user.email 'c0478592@gmail.com'

          # Random jumlah commit antara 10–20
          JUMLAH=$(( ( RANDOM % 11 ) + 10 ))
          echo "Hari ini akan membuat $JUMLAH commit."

          for i in $(seq 1 $JUMLAH)
          do
            echo "Commit ke-$i pada $(date)" >> last_update.txt
            git add last_update.txt
            git commit -m "Auto-commit #$i pada $(date)"

            # Random delay antar commit (30–300 detik)
            JEDA=$(( ( RANDOM % 271 ) + 30 ))
            echo "Tunggu $JEDA detik sebelum commit berikutnya..."
            sleep $JEDA
          done

          git push
