name: Auto Commit

on:
  schedule:
    # Menjalankan setiap hari pukul 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Penting: Fetch semua history agar rebase atau merge berjalan dengan baik
        with:
          fetch-depth: 0 # Mengambil semua history untuk semua branch dan tag

      - name: Create or Update a File for Commit
        run: |
          # Menggunakan '>>' untuk menambahkan ke file (append), bukan menimpa ('>')
          # Ini akan mengurangi kemungkinan konflik jika file ini adalah semacam log.
          echo "Pembaruan terakhir pada $(date)" >> last_update.txt

      - name: Stage and Commit Changes
        run: |
          git config --global user.name 'Yawwnann (Bot)'
          git config --global user.email 'c0478592@gmail.com' # Ganti dengan email yang sesuai
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Auto-commit: Pembaruan terjadwal pada $(date)"
            echo "Perubahan berhasil di-commit."
          else
            echo "Tidak ada perubahan untuk di-commit."
          fi

      - name: Pull Remote Changes and Push
        run: |
          # Cek apakah ada commit yang baru saja dibuat oleh workflow ini
          if git log -1 --pretty=%B | grep -q "Auto-commit"; then
            echo "Ada commit baru dari 'Auto-commit'."

            # Sinkronkan dengan perubahan dari remote sebelum push
            # Menggunakan rebase untuk menjaga history lebih linear.
            echo "Melakukan pull dari remote dengan rebase..."
            # Jika Anda terus mengalami konflik dengan rebase bahkan setelah append,
            # Anda bisa mencoba 'git pull' (merge) sebagai alternatif,
            # atau mempertimbangkan strategi resolusi konflik otomatis jika sesuai.
            git pull --rebase # Atau git pull (untuk merge)

            echo "Mendorong perubahan ke remote..."
            git push
            echo "Perubahan berhasil di-push."
          else
            echo "Tidak ada commit baru dari 'Auto-commit' untuk di-push atau tidak ada perubahan."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
